### PR TITLE
Fix DNS issue

### LINKED ISSUE #12: facing error

### PR DESCRIPTION
**Pull request by DeicPro**
This fix #12 also #11

### CODE REVIEW

**Review by DeicPro — COMMENTED** [review]
Also #11

**Comment by Zeioth** [comment]
I can confirm the issue is there, and this PR fixes it.

Tested on a Samsung Galaxy Fold 3.

**Comment by Zeioth** [comment]
In the meantime I've merged this PR [here](https://github.com/egandro/docker-qemu-arm/pull/14). 

## Other improvements

* I've made it executable in all sh/bash/zsh.
* Uses ALPINE_ISO_URL v3.17
* README has instructions to install portainer (taken from [here](https://github.com/mrp-yt/docker_and_portainer_on_dex))

**Comment by egandro** [comment]
@DeicPro thx for your Pull Request.

Can we have the IP addresss a bit more flexible? e.g. put them in variables. I know a lot of ISPs or Internet Boxes or Internet Cafés might use the IPs you picked.

The DNS Issues might have a diffferent reason: https://github.com/k3s-io/k3s/issues/6132

I am currently getting mad in a kubernets project, where Alpine Linux behaves just bad because of some issues they have with the  DNS caused by musl. Alpine DNS resolution doesn't stop at the "first" DNS server found it uses somehow round robin. Sometimes a ipv4 (only) based system then try to download stuff from an ipv6 host.

That is what your "fix" (make it ipv4 with a static ip) is eventualy effective - it's not the foundation of the fix it's a kind of workaround (for an Alpine bug)

Do you think we should switch to ubuntu/debian? That might be 100-150mb more download.

**Comment by egandro** [comment]
I updated my script and fixed the alpine DNS issues.

Please test - I will close this PR here, as your changes migh no longer work.

**Pull request closed without merging**
